### ISSUE TITLE
some image-mask seem to overlap two different source images

### ISSUE THREAD

**Issue by RubReh** [minar09/cp-vton-plus#8]
When I run body_binary_masking.py on the test set some masks seem to consist of two different images. However, many images also appear normal. Is this a known issue?

See below for an example:

![000266_0](https://user-images.githubusercontent.com/38507268/89016719-7a6f9e80-d319-11ea-9b83-1ba28fe212d4.png)

![000258_0](https://user-images.githubusercontent.com/38507268/89016704-75125400-d319-11ea-84ae-044eefaf98ff.png)

Thanks for a great implementation otherwise!

**Comment by minar09** [comment]
Hi @RubReh , no this is not a known issue.  However, many people has similar issues with dataset_neck_correction.py too. Can you please check your inputs and debug these samples maybe? Thanks.

**Comment by RubReh** [comment]
Yes! Will check it and get back to you!

**Comment by RubReh** [comment]
It turned out to be simple. I believe the order in the listdir command is operating system dependant. This causes the segmentation file list and image file list to be appear out of order. A simple sort() on the file lists did the trick. Would you like me to pull request this fix as it might help others? (I am running on MacOS X)

**Comment by minar09** [comment]
Hi @RubReh , thank you very much for your efforts. I was thinking that the listdir might cause an issue but it was running fine on windows so lazily kept as it is. Yes, you're very welcome to submit a pull request.  I guess it will fix the issues in linux and colab also. Yes, the path setting is also correct. Can you please submit the fix for both files, i.e., dataset neck correction and body binary masking? Thank you so much again. Regards.

**Comment by minar09** [comment]
Closing the issue as its resolved. Feel free to reopen in case there are still problems.
